=== David23242/E-Sports/LMSG/Fase 3/Jornadas/jornadasdtd.dtd
<!-- Este seria el DTD -->
<!-- Definimos el elemento padre , sus atributos y elementos -->
<!ELEMENT jornadas (jornada+)>
<!ATTLIST jornada id CDATA #REQUIRED>
<!-- Definimos los atributos para poner enlazar el xsd -->
<!ATTLIST jornadas xmlns:xsi CDATA #REQUIRED>
<!ATTLIST jornadas xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT jornada (numero_jornada+,fecha_jornada+,competicion-info+ )>
<!ELEMENT numero_jornada (#PCDATA)>
<!ELEMENT fecha_jornada (#PCDATA)>
<!-- Definimos otro elmento el cual contiene informacion-->
<!ELEMENT competicion-info (competicion+)>
<!-- Definimos otro elemento con sus atributos y elementos -->
<!ELEMENT competicion (nombre-competicion+, fecha-inicio+,fecha-fin+,etapa+,juego+,ganador?)>
<!ATTLIST competicion id CDATA #REQUIRED>
<!ELEMENT nombre-competicion (#PCDATA)>
<!ELEMENT fecha-inicio (#PCDATA)>
<!ELEMENT fecha-fin (#PCDATA)>
<!ELEMENT etapa (#PCDATA)>
<!ELEMENT juego (#PCDATA)>
<!ELEMENT ganador (#PCDATA)>

=== David23242/E-Sports/LMSG/Fase 3/Jornadas/jornadas.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Fichero para jornadas -->
<!-- Enlazamos el dtd -->
<!DOCTYPE jornadas SYSTEM "jornadasdtd.dtd">
<!-- Enlazamos el xsd -->
<jornadas
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="jornadasxsd.xsd">
    <jornada id="1">
        <numero_jornada>1</numero_jornada>
        <fecha_jornada>2024-05-10</fecha_jornada>
        <competicion-info>
            <competicion id="1">
                <nombre-competicion>CS2 MAJOR COPENHAGEN 2024</nombre-competicion>
                <fecha-inicio>2024-05-05</fecha-inicio>
                <fecha-fin>2024-06-05</fecha-fin>
                <etapa>A</etapa>
                <juego>Counter-Strike series</juego>
            </competicion>
        </competicion-info>
    </jornada>
    <jornada id="2">
        <numero_jornada>2</numero_jornada>
        <fecha_jornada>2024-05-17</fecha_jornada>
        <competicion-info>
            <competicion id="3">
                <nombre-competicion>CS2 MAJOR COPENHAGEN 2024</nombre-competicion>
                <fecha-inicio>2024-05-05</fecha-inicio>
                <fecha-fin>2024-06-05</fecha-fin>
                <etapa>C</etapa>
                <juego>Counter-Strike series</juego>
            </competicion>
        </competicion-info>
    </jornada>
</jornadas>
