<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jornadas [
    <!ELEMENT jornadas (jornada+)>
    <!ELEMENT jornada (idJornada, numJornada, fechaJornada, idCompeticion, enfrentamientos)>
    <!ELEMENT idJornada (#PCDATA)>
    <!ELEMENT numJornada (#PCDATA)>
    <!ELEMENT fechaJornada (#PCDATA)>
    <!ELEMENT idCompeticion (#PCDATA)>
    <!ELEMENT enfrentamientos (enfrentamiento+)>
    <!ELEMENT enfrentamiento (equipo1, equipo2, resultado)>
    <!ELEMENT equipo1 (#PCDATA)>
    <!ELEMENT equipo2 (#PCDATA)>
    <!ELEMENT resultado (#PCDATA)>
]>
<jornadas>

    <jornada>
        <idJornada>1</idJornada>
        <numJornada>1</numJornada>
        <fechaJornada>1 de enero de 2025</fechaJornada>
        <idCompeticion>1</idCompeticion>
        <enfrentamientos>
            <enfrentamiento>
                <equipo1>Equipo1</equipo1>
                <equipo2>Equipo2</equipo2>
                <resultado>0-0</resultado>
            </enfrentamiento>
        </enfrentamientos>
    </jornada>

    <jornada>
        <idJornada>2</idJornada>
        <numJornada>2</numJornada>
        <fechaJornada>8 de enero de 2025</fechaJornada>
        <idCompeticion>1</idCompeticion>
        <enfrentamientos>
            <enfrentamiento>
                <equipo1>Equipo1</equipo1>
                <equipo2>Equipo2</equipo2>
                <resultado>4-2</resultado>
            </enfrentamiento>
        </enfrentamientos>
    </jornada>

    <jornada>
        <idJornada>3</idJornada>
        <numJornada>3</numJornada>
        <fechaJornada>15 de enero de 2025</fechaJornada>
        <idCompeticion>1</idCompeticion>
        <enfrentamientos>
            <enfrentamiento>
                <equipo1>Equipo1</equipo1>
                <equipo2>Equipo2</equipo2>
                <resultado>2-3</resultado>
            </enfrentamiento>
        </enfrentamientos>
    </jornada>

</jornadas>