=== David23242/E-Sports/LMSG/Fase 3/Clasificacion/clasificaciondtd.dtd
<!-- Este seria el DTD -->
<!-- Definimos el elemento padre , sus atributos y elementos -->
<!ELEMENT clasificacion (nombre_competicion+, nombre_juego+, equipo+)>
<!ATTLIST clasificacion id CDATA #REQUIRED>
<!-- Definimos los atributos para poner enlazar el xsd -->
<!ATTLIST clasificacion xmlns:xsi CDATA #REQUIRED>
<!ATTLIST clasificacion xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT nombre_competicion (#PCDATA)>
<!ELEMENT nombre_juego (#PCDATA)>
<!-- Definimos otro elemento con sus atributos y elementos -->
<!ELEMENT equipo (nombre_equipo+, victorias+, puntos+)>
<!ATTLIST equipo id_equipo CDATA #REQUIRED>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT victorias (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>

=== David23242/E-Sports/LMSG/Fase 3/Clasificacion/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Fichero para clasificacion -->
<!-- Enlazamos el dtd -->
<!DOCTYPE clasificacion SYSTEM "clasificaciondtd.dtd">
<!-- Enlazamos el xsd -->
<clasificacion id="1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clasificacionxsd.xsd">
    <nombre_competicion>CS2 MAJOR COPENHAGEN 2024</nombre_competicion>
    <nombre_juego>Counter-Strike series</nombre_juego>
    <equipo id_equipo="17">
        <nombre_equipo>Team Heretics</nombre_equipo>
        <victorias>9</victorias>
        <puntos>45</puntos>
    </equipo>
    <equipo id_equipo="3">
        <nombre_equipo>Evil Geniuses</nombre_equipo>
        <victorias>8</victorias>
        <puntos>18</puntos>
    </equipo>
    <equipo id_equipo="20">
        <nombre_equipo>INTZ</nombre_equipo>
        <victorias>6</victorias>
        <puntos>21</puntos>
    </equipo>
</clasificacion>
